spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Orbit@1234
  jpa:
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000